SELECT C.CAR_ID, C.CAR_TYPE, TRUNCATE(C.DAILY_FEE*(100-DISCOUNT_RATE)/100*30,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON H.CAR_ID = C.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE
AND C.CAR_TYPE IN ('세단','SUV') AND P.DURATION_TYPE = '30일 이상'
GROUP BY 1
HAVING (MAX(END_DATE) < '2022-11-01') AND FEE between 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC


