SELECT D.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, D.APNT_YMD
FROM PATIENT P
JOIN (SELECT A.APNT_NO, A.MCDP_CD, T.DR_NAME, A.APNT_YMD, A.PT_NO
      FROM APPOINTMENT A
      JOIN DOCTOR T
      ON A.MDDR_ID = T.DR_ID
      WHERE A.APNT_CNCL_YN = 'N' AND A.APNT_YMD LIKE '2022-04-13%'
     ) D
ON P.PT_NO = D.PT_NO
ORDER BY D.APNT_YMD;
